### ISSUE TITLE
`sidekick` commands should have help messages

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-rust#393]
As the number of commands grows we may need some help to tell what commands do what.

----
Can we file a bug to add help text for these different commands?

_Originally posted by @codyoss in https://github.com/googleapis/google-cloud-rust/pull/391#discussion_r1878328859_

**Comment by coryan** [comment]
@julieqiu I think I heard you say that you had thoughts on how to better structure the commands in `sidekick`?

**Comment by julieqiu** [comment]
Borrowing from [cmd/go/internal/base.Command](https://github.com/golang/go/blob/d87878c62b2db318a12e5bd2126a82c117961156/src/cmd/go/internal/base/base.go#L28), you could represent each of these [subcommands](https://github.com/googleapis/google-cloud-rust/blob/main/generator/internal/sidekick/sidekick.go#L63-L70) as its own command, so that they each have their own description and flag.FlagSet. Here is a similar implementation in the generator repo:

https://github.com/googleapis/generator/blob/main/internal/generate/flags.go

Happy to send a PR if you want to go in this direction.

**Comment by coryan** [comment]
> Happy to send a PR if you want to go in this direction.

Please do.  I am trying to get some Rusty stuff done.
